version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: sampahkitajabar-be
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8081:8081"
    networks:
      - sampahkitajabar

  mysql:
    image: mysql
    container_name: sampahkitajabar-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sampahkitajabar
      MYSQL_ROOT_PASSWORD: e91271f03015ff1be85b692a1a2b0875
      MYSQL_USER: sampahkitajabar
      MYSQL_PASSWORD: P4@ssword!
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "8081:8081"
    networks:
      - sampahkitajabar

networks:
  sampahkitajabar:

volumes:
  mysql_data:
